package ledger

import (
	"crypto/rand"
	"encoding/hex"
)

// newID returns a prefixed, random identifier such as "ltx_9f2c...".
//
// IDs are generated by the application, not by a database DEFAULT, because a
// caller must know the id before the row is written: phase 5 writes an outbox
// event referencing the transaction inside the same transaction.
//
// crypto/rand rather than math/rand: ids appear in URLs and logs, and a
// guessable id is an enumeration hole the moment this is an API.
func newID(prefix string) string {
	var b [16]byte
	// rand.Read is documented never to return an error; it panics internally
	// on a broken entropy source rather than returning short reads.
	rand.Read(b[:])
	return prefix + "_" + hex.EncodeToString(b[:])
}
