package auth

import (
	"context"
	"crypto/rand"
	"encoding/hex"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
)

// Querier and Execer are satisfied by a pool, a connection and a transaction
// alike, so every function here can run inside a caller's transaction. Phase 2
// needs that: POST /transfers writes the transfer and its ledger entries in one
// transaction, and phase 5 adds an outbox row to the same one.
type Querier interface {
	QueryRow(ctx context.Context, sql string, args ...any) pgx.Row
}

type Execer interface {
	Exec(ctx context.Context, sql string, args ...any) (pgconn.CommandTag, error)
}

// newID returns a prefixed random identifier, generated by the application
// rather than a database DEFAULT so a caller knows the id before the insert.
func newID(prefix string) string {
	var b [16]byte
	_, _ = rand.Read(b[:])
	return prefix + "_" + hex.EncodeToString(b[:])
}
